const createCommunityMapEntry = (id, title, sourceName, pinsSlug = id) => ({
	id,
	title,
	mapConfig: {
		viewWidth: 1400,
		viewHeight: 840,
		hexSize: 14,
		sourceUrl: `/community/${sourceName}.Civ5Map`,
		baseCacheUrl: `/community/${sourceName}.base.json`,
		maxScale: 3,
	},
	pinsUrl: `/maps/${pinsSlug}.pins.json`,
});

export const maps = [
	{
		id: "afri-asia-aust",
		title: "Afri Asia Aust",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfriAsiaAust.Civ5Map",
			baseCacheUrl: "/community/AfriAsiaAust.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/afri-asia-aust.pins.json",
		labelsUrl: "/maps/afri-asia-aust.labels.json",
	},
	{
		id: "africa-large",
		title: "Africa Large",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfricaLarge.Civ5Map",
			baseCacheUrl: "/community/AfricaLarge.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/africa-large.pins.json",
	},
	{
		id: "afri-south-euro",
		title: "Afri South Euro",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfriSouthEuro.Civ5Map",
			baseCacheUrl: "/community/AfriSouthEuro.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/afri-south-euro.pins.json",
	},
	{
		id: "americas",
		title: "Americas",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Americas.Civ5Map",
			baseCacheUrl: "/community/Americas.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/americas.pins.json",
	},
	{
		id: "apennine",
		title: "Apennine",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Apennine.Civ5Map",
			baseCacheUrl: "/community/Apennine.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/apennine.pins.json",
	},
	{
		id: "asia",
		title: "Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Asia.Civ5Map",
			baseCacheUrl: "/community/Asia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/asia.pins.json",
	},
	{
		id: "british-isles",
		title: "British Isles",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/BritishIsles.Civ5Map",
			baseCacheUrl: "/community/BritishIsles.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/british-isles.pins.json",
	},
	{
		id: "caribbean",
		title: "Caribbean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Caribbean.Civ5Map",
			baseCacheUrl: "/community/Caribbean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/caribbean.pins.json",
	},
	{
		id: "cordiform",
		title: "Cordiform",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Cordiform.Civ5Map",
			baseCacheUrl: "/community/Cordiform.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/cordiform.pins.json",
	},
	{
		id: "earth-mk3",
		title: "Earth Mk3",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EarthMk3.Civ5Map",
			baseCacheUrl: "/community/EarthMk3.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/earth-mk3.pins.json",
	},
	{
		id: "east-asia",
		title: "East Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EastAsia.Civ5Map",
			baseCacheUrl: "/community/EastAsia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/east-asia.pins.json",
	},
	{
		id: "euro-large",
		title: "Euro Large",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EuroLarge.Civ5Map",
			baseCacheUrl: "/community/EuroLarge.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/euro-large.pins.json",
	},
	{
		id: "euro-large-new",
		title: "Euro Large New",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EuroLargeNew.Civ5Map",
			baseCacheUrl: "/community/EuroLargeNew.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/euro-large-new.pins.json",
	},
	{
		id: "greatest-earth",
		title: "Greatest Earth",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/GreatestEarth.Civ5Map",
			baseCacheUrl: "/community/GreatestEarth.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/greatest-earth.pins.json",
	},
	{
		id: "indian-ocean",
		title: "Indian Ocean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/IndianOcean.Civ5Map",
			baseCacheUrl: "/community/IndianOcean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/indian-ocean.pins.json",
	},
	{
		id: "mediterranean",
		title: "Mediterranean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Mediterranean.Civ5Map",
			baseCacheUrl: "/community/Mediterranean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/mediterranean.pins.json",
	},
	{
		id: "mesopotamia",
		title: "Mesopotamia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Mesopotamia.Civ5Map",
			baseCacheUrl: "/community/Mesopotamia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/mesopotamia.pins.json",
	},
	{
		id: "north-atlantic",
		title: "North Atlantic",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthAtlantic.Civ5Map",
			baseCacheUrl: "/community/NorthAtlantic.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-atlantic.pins.json",
	},
	{
		id: "north-east-asia",
		title: "North East Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthEastAsia.Civ5Map",
			baseCacheUrl: "/community/NorthEastAsia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-east-asia.pins.json",
	},
	{
		id: "north-west-europe",
		title: "North West Europe",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthWestEurope.Civ5Map",
			baseCacheUrl: "/community/NorthWestEurope.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-west-europe.pins.json",
	},
	{
		id: "orient",
		title: "Orient",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Orient.Civ5Map",
			baseCacheUrl: "/community/Orient.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/orient.pins.json",
	},
	{
		id: "south-pacific",
		title: "South Pacific",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/SouthPacific.Civ5Map",
			baseCacheUrl: "/community/SouthPacific.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/south-pacific.pins.json",
	},
	{
		id: "yagem",
		title: "Yagem",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Yagem.Civ5Map",
			baseCacheUrl: "/community/Yagem.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/yagem.pins.json",
	},
	{
		id: "yahem",
		title: "Yahem",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Yahem.Civ5Map",
			baseCacheUrl: "/community/Yahem.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/yahem.pins.json",
	},
	{
		id: "cbrx",
		title: "CBRX S5",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/CBRXMapOct62025_V2.civ5map",
			baseCacheUrl: "/community/CBRXMapOct62025_V2.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/cbrx.pins.json",
	},
	{
		id: "endgame-final-unitless-resources",
		title: "CBRX Endgame",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EndgameFinalUnitlessResources.Civ5Map",
			baseCacheUrl: "/community/EndgameFinalUnitlessResources.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/endgame-final-unitless-resources.pins.json",
	},
	{
		id: "mini-cbrx",
		title: "Mini CBRX",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/MiniCBRX.Civ5Map",
			baseCacheUrl: "/community/MiniCBRX.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/mini-cbrx.pins.json",
	},
	{
		id: "lung-south-asia-1",
		title: "Lung's South Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/LungSouthAsia(1).Civ5Map",
			baseCacheUrl: "/community/LungSouthAsia(1).base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/lung-south-asia-1.pins.json",
	},
	{
		id: "monsoon",
		title: "Monsoon Season",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/monsoon.Civ5Map",
			baseCacheUrl: "/community/monsoon.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/monsoon.pins.json",
	},
	{
		id: "gerstein-goons-north-american-pacific-coast-map",
		title: "Gerstein's California",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/gerstein_goon's North American Pacific Coast Map.Civ5Map",
			baseCacheUrl: "/community/gerstein_goon's North American Pacific Coast Map.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/gerstein-goons-north-american-pacific-coast-map.pins.json",
	},
	{
		id: "crossroads-of-eurasia",
		title: "Crossroads of Eurasia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/CrossroadsofEurasia.Civ5Map",
			baseCacheUrl: "/community/CrossroadsofEurasia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/crossroads-of-eurasia.pins.json",
	},
	{
		id: "cbrx-large-denmark-tonga",
		title: "Large Earth",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/CBRX Large Denmark Tonga.Civ5Map",
			baseCacheUrl: "/community/CBRX Large Denmark Tonga.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/cbrx-large-denmark-tonga.pins.json",
	},
	createCommunityMapEntry("adriatic", "Adriatic", "Adriatic"),
	createCommunityMapEntry("aegean", "Aegean", "Aegean"),
	createCommunityMapEntry("afri-giant", "Afri Giant", "AfriGiant"),
	createCommunityMapEntry("americas-giant", "Americas Giant", "AmericasGiant"),
	createCommunityMapEntry("asia-small", "Asia Small", "AsiaSmall"),
	createCommunityMapEntry("asia-steppe-giant", "Asia Steppe Giant", "AsiaSteppeGiant"),
	createCommunityMapEntry("atlantic-giant", "Atlantic Giant", "AtlanticGiant"),
	createCommunityMapEntry("australasia-giant", "Australasia Giant", "AustralasiaGiant"),
	createCommunityMapEntry("australia", "Australia", "Australia"),
	createCommunityMapEntry("caribbean-huge", "Caribbean Huge", "CaribbeanHuge"),
	createCommunityMapEntry("caucasus", "Caucasus", "Caucasus"),
	createCommunityMapEntry("central-africa-large", "Central Africa Large", "CentralAfricaLarge"),
	createCommunityMapEntry("central-asia", "Central Asia", "CentralAsia"),
	createCommunityMapEntry("denmark", "Denmark", "Denmark"),
	createCommunityMapEntry("euro-eastern", "Euro Eastern", "EuroEastern"),
	createCommunityMapEntry("euro-giant", "Euro Giant", "EuroGiant"),
	createCommunityMapEntry("germany-huge", "Germany Huge", "GermanyHuge"),
	createCommunityMapEntry("iberia", "Iberia", "Iberia"),
	createCommunityMapEntry("india", "India", "India"),
	createCommunityMapEntry("india-giant", "India Giant", "IndiaGiant"),
	createCommunityMapEntry("indonesia", "Indonesia", "Indonesia"),
	createCommunityMapEntry("japan-huge", "Japan Huge", "JapanHuge"),
	createCommunityMapEntry("levant", "Levant", "Levant"),
	createCommunityMapEntry("mediterranean-huge", "Mediterranean Huge", "MediterraneanHuge"),
	createCommunityMapEntry("mesopotamia-giant", "Mesopotamia Giant", "MesopotamiaGiant"),
	createCommunityMapEntry("netherlands", "Netherlands", "Netherlands"),
	createCommunityMapEntry("nile-valley", "Nile Valley", "NileValley"),
	createCommunityMapEntry("north-america-giant", "North America Giant", "NorthAmericaGiant"),
	createCommunityMapEntry("north-america-huge", "North America Huge", "NorthAmericaHuge"),
	createCommunityMapEntry("north-sea-europe", "North Sea Europe", "NorthSeaEurope"),
	createCommunityMapEntry("north-sea-giant", "North Sea Giant", "NorthSeaGiant"),
	createCommunityMapEntry("pacific", "Pacific", "Pacific"),
	createCommunityMapEntry("patagonia", "Patagonia", "Patagonia"),
	createCommunityMapEntry("russia-large", "Russia Large", "RussiaLarge"),
	createCommunityMapEntry("scotland-ireland-huge", "Scotland Ireland Huge", "ScotlandIrelandHuge"),
	createCommunityMapEntry("sea-of-japan", "Sea of Japan", "SeaOfJapan"),
	createCommunityMapEntry("south-america-central-giant", "South America Central Giant", "SouthAmericaCentralGiant"),
	createCommunityMapEntry("south-america-central-huge", "South America Central Huge", "SouthAmericaCentralHuge"),
	createCommunityMapEntry("south-america-giant", "South America Giant", "SouthAmericaGiant"),
	createCommunityMapEntry("south-america-large", "South America Large", "SouthAmericaLarge"),
	createCommunityMapEntry("south-asia-huge", "South Asia Huge", "SouthAsiaHuge"),
	createCommunityMapEntry("southern-africa", "Southern Africa", "SouthernAfrica"),
	createCommunityMapEntry("south-pacific-giant", "South Pacific Giant", "SouthPacificGiant"),
	createCommunityMapEntry("texcoco", "Texcoco", "Texcoco"),
	createCommunityMapEntry("vietnam", "Vietnam", "Vietnam"),
	createCommunityMapEntry("wales", "Wales", "Wales"),
	createCommunityMapEntry("west-africa", "West Africa", "WestAfrica"),
];
