export const maps = [
	{
		id: "afri-asia-aust",
		title: "Afri Asia Aust",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfriAsiaAust.Civ5Map",
			baseCacheUrl: "/community/AfriAsiaAust.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/afri-asia-aust.pins.json",
		labelsUrl: "/maps/afri-asia-aust.labels.json",
	},
	{
		id: "africa-large",
		title: "Africa Large",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfricaLarge.Civ5Map",
			baseCacheUrl: "/community/AfricaLarge.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/africa-large.pins.json",
	},
	{
		id: "afri-south-euro",
		title: "Afri South Euro",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/AfriSouthEuro.Civ5Map",
			baseCacheUrl: "/community/AfriSouthEuro.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/afri-south-euro.pins.json",
	},
	{
		id: "americas",
		title: "Americas",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Americas.Civ5Map",
			baseCacheUrl: "/community/Americas.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/americas.pins.json",
	},
	{
		id: "apennine",
		title: "Apennine",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Apennine.Civ5Map",
			baseCacheUrl: "/community/Apennine.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/apennine.pins.json",
	},
	{
		id: "asia",
		title: "Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Asia.Civ5Map",
			baseCacheUrl: "/community/Asia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/asia.pins.json",
	},
	{
		id: "british-isles",
		title: "British Isles",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/BritishIsles.Civ5Map",
			baseCacheUrl: "/community/BritishIsles.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/british-isles.pins.json",
	},
	{
		id: "caribbean",
		title: "Caribbean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Caribbean.Civ5Map",
			baseCacheUrl: "/community/Caribbean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/caribbean.pins.json",
	},
	{
		id: "cordiform",
		title: "Cordiform",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Cordiform.Civ5Map",
			baseCacheUrl: "/community/Cordiform.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/cordiform.pins.json",
	},
	{
		id: "earth-mk3",
		title: "Earth Mk3",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EarthMk3.Civ5Map",
			baseCacheUrl: "/community/EarthMk3.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/earth-mk3.pins.json",
	},
	{
		id: "east-asia",
		title: "East Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EastAsia.Civ5Map",
			baseCacheUrl: "/community/EastAsia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/east-asia.pins.json",
	},
	{
		id: "euro-large",
		title: "Euro Large",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EuroLarge.Civ5Map",
			baseCacheUrl: "/community/EuroLarge.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/euro-large.pins.json",
	},
	{
		id: "euro-large-new",
		title: "Euro Large New",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/EuroLargeNew.Civ5Map",
			baseCacheUrl: "/community/EuroLargeNew.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/euro-large-new.pins.json",
	},
	{
		id: "greatest-earth",
		title: "Greatest Earth",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/GreatestEarth.Civ5Map",
			baseCacheUrl: "/community/GreatestEarth.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/greatest-earth.pins.json",
	},
	{
		id: "indian-ocean",
		title: "Indian Ocean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/IndianOcean.Civ5Map",
			baseCacheUrl: "/community/IndianOcean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/indian-ocean.pins.json",
	},
	{
		id: "mediterranean",
		title: "Mediterranean",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Mediterranean.Civ5Map",
			baseCacheUrl: "/community/Mediterranean.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/mediterranean.pins.json",
	},
	{
		id: "mesopotamia",
		title: "Mesopotamia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Mesopotamia.Civ5Map",
			baseCacheUrl: "/community/Mesopotamia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/mesopotamia.pins.json",
	},
	{
		id: "north-atlantic",
		title: "North Atlantic",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthAtlantic.Civ5Map",
			baseCacheUrl: "/community/NorthAtlantic.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-atlantic.pins.json",
	},
	{
		id: "north-east-asia",
		title: "North East Asia",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthEastAsia.Civ5Map",
			baseCacheUrl: "/community/NorthEastAsia.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-east-asia.pins.json",
	},
	{
		id: "north-west-europe",
		title: "North West Europe",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/NorthWestEurope.Civ5Map",
			baseCacheUrl: "/community/NorthWestEurope.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/north-west-europe.pins.json",
	},
	{
		id: "orient",
		title: "Orient",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Orient.Civ5Map",
			baseCacheUrl: "/community/Orient.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/orient.pins.json",
	},
	{
		id: "south-pacific",
		title: "South Pacific",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/SouthPacific.Civ5Map",
			baseCacheUrl: "/community/SouthPacific.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/south-pacific.pins.json",
	},
	{
		id: "yagem",
		title: "Yagem",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Yagem.Civ5Map",
			baseCacheUrl: "/community/Yagem.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/yagem.pins.json",
	},
	{
		id: "yahem",
		title: "Yahem",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/Yahem.Civ5Map",
			baseCacheUrl: "/community/Yahem.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/yahem.pins.json",
	},
	{
		id: "cbrx",
		title: "CBRX S5",
		mapConfig: {
			viewWidth: 1400,
			viewHeight: 840,
			hexSize: 14,
			sourceUrl: "/community/CBRXMapOct62025_V2.civ5map",
			baseCacheUrl: "/community/CBRXMapOct62025_V2.base.json",
			maxScale: 3,
		},
		pinsUrl: "/maps/cbrx.pins.json",
		// labelsUrl: "/maps/cbrx.labels.json",
	},
];
